<?php
const TEMP_TEXT = [
0 => 'Are you looking for specialty coffee?',
1 => 'Find the providers you need quickly.',
2 => 'Back to top',
3 => 'Preference',
4 => 'About Wuwana',
5 => 'Our privacy policy',
6 => 'We ❤️ Open Source',
7 => 'Search for a company',
8 => 'Finding the information you need should be easier.',
9 => 'Contact us',
10 => 'Hello, visitor!',
11 => 'Homepage',
12 => 'Logout',
13 => 'Admin controls',
14 => 'Please login',
15 => 'You need to login to access this section.',
16 => 'Email',
17 => 'Code',
18 => 'Login',
19 => 'Website Language',
20 => 'Online Directory',
21 => 'Go back',
22 => 'Light Mode',
23 => 'Dark Mode',
];