<?php
const TEMP_TEXT = [
0 => '¿Estás buscando café de especialidad?',
1 => 'Encuentra los proveedores que necesitas rápidamente.',
2 => 'Volver arriba',
3 => 'Idioma',
4 => 'Sobre Wuwana',
5 => 'Política de privacidad',
6 => 'We ❤️ Open Source',
7 => 'Busca una empresa',
8 => 'Encontrar la información que necesitas debería ser más fácil.',
9 => 'Contáctanos',
10 => '¡Hola, visitante!',
11 => 'Página de inicio',
12 => 'Cierre de sesión',
13 => 'Controles de administración',
14 => 'Por favor, inicie sesión',
15 => 'Necesita iniciar sesión para acceder a esta sección',
16 => 'Correo electrónico',
17 => 'Código',
18 => 'Login',
19 => 'Idioma de la página web',
20 => 'Directorio',
];