<?php
const TEMP_TEXT = [
0 => "Vous cherchez un torréfacteur de café spécialisé ?",
1 => "Trouvez rapidement les fournisseurs dont vous avez besoin.",
2 => "Retour au début",
3 => "Langue",
4 => "À propos de Wuwana™",
5 => "Politiques de confidentialité",
6 => "We ❤️ Open Source",
7 => "Trouvez le fournisseur dont vous avez besoin",
8 => "Trouver les informations dont vous avez besoin devrait être plus facile",
9 => "Contactez-nous",
10 => 'Bonjour, visiteur !',
11 => "Page d'accueil",
12 => 'Déconnexion',
13 => 'Contrôles administrateurs',
14 => 'Veuillez vous connecter',
15 => 'Vous devez vous connecter pour accéder à cette section',
16 => 'Email',
17 => 'Code',
18 => 'Login',
];