<?php
const TEXT = [
0 => 'Specialty coffee',
1 => 'Categories',
2 => 'All categories',
3 => 'Regions',
4 => 'All regions',
5 => 'Companies',
6 => 'View more',
7 => 'Apply filter',
8 => 'Filter options',
9 => 'Try searching for the product you need, the industry you want or the name of a company',
10 => 'What is Wuwana?',
11 => 'Suggested searches',
12 => '⚠️ Warning ⚠️: this site is under construction. Some information might not be correct.',
13 => 'Showing %s results for',
14 => 'Filter',
15 => "We didn’t find anything for <span>%s</span>. Try modifying your search or browse our suggested searches.",
// 16 => ' results for',
17 => 'Specialty coffee',
18 => 'Beer',
19 => 'Coffee roaster',
20 => 'Coffee shop',
21 => 'Home',
22 => 'How to use this website?',
];