<?php
const TEXT = [
0 => 'Café de especialidad',
1 => 'Categorías',
2 => 'Todas las categorías',
3 => 'Comunidades autónomas',
4 => 'Todas las comunidades',
5 => 'Empresas',
6 => 'Ver más empresas',
7 => 'Aplicar filtros',
8 => 'Personaliza la búqueda',
9 => 'Busca el producto que necesita, el sector que desea o el nombre de una empresa',
10 => 'Descubre qué es Wuwana',
11 => 'Sugerencias',
12 => '⚠️ Advertencia ⚠️: este sitio está en construcción. Alguna información podría no ser correcta.',
13 => 'Mostrando %s resultados para',
14 => 'Filtro',
15 => "No hemos encontrado nada para <span>%s</span>. Intente modificar su búsqueda o consulte nuestras sugerencias.",
// 16 => ' resultados para',
17 => 'Café de especialidad',
18 => 'Cerveza',
19 => 'Tostador',
20 => 'Cafetería',
21 => 'Principal',
22 => '¿Cómo usar esta página?',
23 => 'Resultados',
];