<?php
const TEXT = [
0 => "Café spécialisé",
1 => "Catégories",
2 => "Toutes les catégories",
3 => "Régions",
4 => "Toutes les régions",
5 => "Entreprises",
6 => "Voir plus",
7 => "Appliquer les filtres",
8 => "Options de filtrage",
9 => "Essayez de rechercher le produit dont vous avez besoin, le secteur d'activité que vous souhaitez ou le nom d'une entreprise",
10 => "Qu'est-ce que Wuwana?",
11 => "Recherche suggérée",
12 => '⚠️ Attention ⚠️: ce site est en construction. Certaines informations peuvent ne pas être correctes',
//13 => 'Bonjour, visiteur !',
14 => 'Filtre',
15 => '',
16 => ' résultats pour',
17 => 'Café de spécialité',
18 => 'Bière',
19 => 'Torréfacteur de café',
20 => 'Boutique de café',
];